#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias b='bundle exec'
alias copy='tmux showb | pbcopy'

export PATH="$PATH:$HOME/.rvm/bin:$HOME/Library/Haskell/bin"

source ~/.zsh-nvm/zsh-nvm.plugin.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

setopt noincappendhistory
setopt nosharehistory
